# Generated by Django 2.2 on 2019-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('realm', models.TextField()),
                ('account', models.IntegerField()),
                ('bank_num', models.IntegerField()),
                ('bank_gold', models.IntegerField()),
                ('trade_timestamp', models.IntegerField()),
                ('trade_confirmation', models.IntegerField()),
            ],
            options={
                'db_table': 'bankers',
                'managed': False,
            },
        ),
    ]
