# Generated by Django 2.2 on 2019-08-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('realm', models.TextField()),
                ('code', models.TextField()),
                ('price_per_mil', models.IntegerField()),
            ],
            options={
                'db_table': 'realms',
                'managed': False,
            },
        ),
    ]
