// banker actions
export const FETCH_BANKERS = 'FETCH_BANKERS';
export const FETCH_REALMS = 'FETCH_REALMS';
export const SELECT_BANKER = 'SELECT_BANKER';
export const UPDATE_BANKER = 'UPDATE_BANKER';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const WIPE_TRADE = 'WIPE_TRADE';

// settings
export const TOGGLE_BANKERS_TABLE = 'TOGGLE_BANKERS_TABLE';
export const TOGGLE_TRADED_BANKERS = 'TOGGLE_TRADED_BANKERS';
export const TOGGLE_TRADED_TOOLTIPS = 'TOGGLE_TRADED_TOOLTIPS';
export const TOGGLE_TRADED_OPERATIONS = 'TOGGLE_TRADED_OPERATIONS';
export const TOGGLE_REALM_STATS = 'TOGGLE_REALM_STATS';
export const SELECT_STATS_REALM = 'SELECT_STATS_REALM';
export const SELECT_STATS_CURRENCY = 'SELECT_STATS_CURRENCY';